baseURL = 'https://example.org/'  # 後でドメイン取得後に変更
languageCode = 'ja'
title = 'ワガママエロス'
theme = 'blonde'
defaultContentLanguage = 'ja'

[taxonomies]
  actress = 'actresses'
  genre   = 'genres'
  maker   = 'makers'
  tag     = 'tags'

[markup.goldmark.renderer]
  unsafe = true

[params]
  mainSections = ['posts']
