baseURL = 'https://wagamama-eros.com/'
languageCode = 'ja'
title = 'ワガママエロス'
theme = 'blonde'
defaultContentLanguage = 'ja'
rssLimit = 20

[taxonomies]
  actress  = 'actresses'
  author   = 'authors'
  genre    = 'genres'
  maker    = 'makers'
  tag      = 'tags'
  director = 'directors'
  label    = 'labels'
  series   = 'series'

[markup.goldmark.renderer]
  unsafe = true

[[menu.main]]
  identifier = "home"
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  identifier = "terms"
  name = "利用規約"
  url = "/terms/"
  weight = 2

[[menu.main]]
  identifier = "privacy"
  name = "プライバシーポリシー"
  url = "/privacy/"
  weight = 3

[[menu.main]]
  identifier = "disclaimer"
  name = "免責事項"
  url = "/disclaimer/"
  weight = 4

[[menu.main]]
  identifier = "contact"
  name = "お問い合わせ"
  url = "/contact/"
  weight = 5

[params]
  mainSections = ['post']
  paginator_pages = "12"
  darkmode = "dark"
  description = ""
  tagslimit = 50

  [params.post]
    thumbnail = true
    noimage = true
    thumbnail_height = "lg:h-44"
    thumbnail_width = "lg:w-auto"
    description = "130"

  [params.widgets]
    display = true
    left_widgets = ["dmm_banner", "sidebar_ranking"]
    widgets = ["rss", "search", "genres", "authors", "actresses", "tags", "recent", "archive"]

  [params.rss_widget]
    proxy = "https://rss-proxy.coelacanth9.workers.dev"
    feeds = [
      "https://doucolle.net/feed"
      ,"http://fevian.org/feed/photo.xml"
      ,"https://kimootoko.net/feed"
      ]
    title = "人気の記事"
    count = 10
